name: pop

on:
  workflow_dispatch:

jobs:
  build:
    name: Building...
    runs-on: windows-latest
    timeout-minutes: 999999999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: ltmnger
        run: cmd /c show.bat

      - name: Counter
        run: cmd /c loop.bat
